### ISSUE TITLE
Please tell me whether it is correct for output image?

### ISSUE THREAD

**Issue by Jamie-Cheung** [vinesmsuic/White-box-Cartoonization-PyTorch#2]
![image](https://user-images.githubusercontent.com/100945715/167100365-edde2db8-e3b1-4b9b-a62a-15c38095a363.png)

**Comment by vinesmsuic** [comment]
This looks like due to the lambda content setting being too small. Are you using the latest version of the code?

**Comment by vinesmsuic** [comment]
can u show me your log output that shows the config setting?

**Comment by Jamie-Cheung** [comment]
![image](https://user-images.githubusercontent.com/100945715/167423638-1276f2ec-5b8d-472b-863f-11265e3d83de.png)
**Now, bach size=16. But the result is so bad. Can you tell me the reason ? Thank you.**

**Comment by vinesmsuic** [comment]
I think you are talking about the noise introduced. This is completely normal and can be removed through the guided filter. I did not include the post-processing step in the visualization of train code. In the test code, there will be a post-processing filter to remove those noise.
