### ISSUE TITLE
Some problem(maybe?) occured during training

### ISSUE THREAD

**Issue by frozen-mind** [vinesmsuic/White-box-Cartoonization-PyTorch#3]
![epoch_33_step_547600_io](https://user-images.githubusercontent.com/56190871/184496988-c96e147d-87d0-4e70-ab55-fe56dfa996c0.png)
![epoch_33_step_547600_photo_rep](https://user-images.githubusercontent.com/56190871/184496990-642399b7-da4c-4174-a1cf-c624a084630e.png)
is this normal? or did i set something wrong?

**Comment by frozen-mind** [comment]
> 

btw these two images are from epoch 32

**Comment by vinesmsuic** [comment]
Hi, #2 might help towards your problem

**Comment by frozen-mind** [comment]
> 

oh thx, it is the batch size problem. i think maybe there is something wrong with the code you provided on github, maybe you can check it and fix the problem

**Comment by frozen-mind** [comment]
![image](https://user-images.githubusercontent.com/56190871/190387045-5f266ee7-bf24-4e35-9043-341950a0c0de.png)
hey, i just found out that the batch size of validation data is also 1, should i change this one to 16 as well?

**Comment by vinesmsuic** [comment]
> ![image](https://user-images.githubusercontent.com/56190871/190387045-5f266ee7-bf24-4e35-9043-341950a0c0de.png)
> hey, i just found out that the batch size of validation data is also 1, should i change this one to 16 as well? Or just remain 1 (cause the training result seems good)

The validation is only used for visualization here. The batch size of validation data need not to be changed.

**Comment by frozen-mind** [comment]
> 
lol, what a stupid question i've asked, thx
